spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS employees
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_schema: employees
        format_sql: true
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug

app:
  jwt:
    secret: "H9i7n4VgYz6q1b0mT2x8w+3lYy0r5pQhJf3t9aG2bNc="
    access-token-expiration:  360000000

  endpoints:
    auth:
      base-uri: '/auth'
      register-uri: '/register'
      login-uri: '/login'
    users:
      base-uri: '/users'
      get-user-uri: '/{id}'
      delete-user-uri: '/{id}'
      update-user-uri: '/{id}'
